name: xrpl-amm-clob
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - matplotlib
  - numpy
  - pandas
  - jupyterlab
  - seaborn
  - pytest
  - pytest-cov
  - hypothesis
  - mypy
  - ruff
  - black
  - pip:
      - -e .
